### ISSUE TITLE
Stackage availability

### ISSUE THREAD

**Issue by tmcdonell** [ekmett/unique#1]
Any chance of getting this package onto stackage? It's a dependency of [accelerate](https://github.com/AccelerateHS/accelerate).

**Comment by ekmett** [comment]
I have no particular objection. Hrmm.

**Comment by RyanGlScott** [comment]
Pending https://github.com/fpco/stackage/pull/2416, it will be in Stackage.

**Comment by tmcdonell** [comment]
Thanks! (:

**Comment by tmcdonell** [comment]
Available from lts-8.10.
